<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit86b6386c0da713e7d76e0ead65a48759
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit86b6386c0da713e7d76e0ead65a48759::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit86b6386c0da713e7d76e0ead65a48759::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit86b6386c0da713e7d76e0ead65a48759::$classMap;

        }, null, ClassLoader::class);
    }
}
